# Generated by Django 5.1.6 on 2025-10-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
