# Generated by Django 5.2.7 on 2025-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtime_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='seats_available',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='seats_total',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
