# Generated by Django 5.2.7 on 2025-10-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime_service', '0003_showtime_seats_per_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='seats_per_row',
        ),
    ]
