# Generated by Django 5.2.7 on 2025-10-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0004_alter_seat_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
