# Generated by Django 5.2.7 on 2025-10-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_service", "0005_rename_booked_at_booking_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
